<div id="gallery">
  <header>
  <h1>Gallery</h1>
  <p>Some pictures to inspire you ...</p>
  </header>

  <section class="posts">

<!-- Posts -->
      <?php
      if (!empty($pageData['gallery_image_urls'])) {
        foreach($pageData['gallery_image_urls'] as $imgurl) {
          echo "<article><img class='b-lazy' src='images/FF4D00-0.8.png' data-src='$imgurl' style='display:block; max-height:500px; max-width:500px'/></article>\n";
        }
      }
      ?>
</section>
</div>
