<body class="is-loading">

		<!-- Wrapper -->
			<div id="wrapper" class="fade-in">

				<!-- Intro -->
                                <div id="intro">
                                                <div>
                                                <!-- <a href="#" class="image main"><img src="images/3DWORLDINCPNG_1_.png" alt="3D WORLD INC."/></a> -->
																								<h1 style="margin-top:-430px">3D World INC.</h1>
																								</div>
						<ul class="actions">
							<li><a href="#header" class="button icon solo fa-arrow-down scrolly">Continue</a></li>
						</ul>
					</div>

				<!-- Header -->
					<header id="header">
						<a href="/" class="logo">3D WORLD INC.</a>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li class="active"><a href="/#home">Home</a></li>
                                                        <li ><a style="color:black" href="/static/3D-Floors-Presentation.pptx">Demo</a></li>
                                                        <li><a style="color:black" href="/#3d-flooring">3D Flooring</a></li>
                                                        <li ><a style="color:black" href="/#3d-walls">3D Walls</a></li>
                                                        <li ><a style="color:black" href="/#3d-ceiling">3D Ceiling</a></li>
                                                        <li ><a style="color:black" href="/#gallery">Gallery</a></li>
                                                        <li ><a style="color:black" href="/#contact-us">Contact Us</a></li>
																															</ul>
						<ul class="icons">
							<!-- <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li> -->
							<li><a href="https://www.facebook.com/3dflooringmontreal/" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<!-- <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li> -->
							<!-- <li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li> -->
						</ul>
					</nav>
				<!-- Main -->
					<div id="main">
						<div id="home">
<!-- Featured Post -->
<article class="post featured">
<header>
<h1>Welcome</h1>

</header>
<p>

	We are very happy to see you in our FAIRY TALE 3D WORLD. Take a seat and we’ll take you to the trip from the ocean floor through the deep walls to the endless space sealing.
</br></br>
	3D interior designs are the most spectacular and exciting modern trends that are now coming to North America. It offers the possibility of transforming a room into an environment or a place you dream of. Any picture or image can be incorporated into floors, walls or ceilings that will allow us to create a dramatic change into room and improve the mood.
</br></br>
	Today, 3D interior designs become more and more popular in commercial areas such as daycares, nightclubs and office lobbies. 3D designs are not only look esthetically, materials used in construction of 3D floors, walls and ceilings are eco-friendly, safe and healthy.
</br>
	 </br>

	So, why not to bring another dimension to your live?
</p>
																<ul class="actions">
																		<li style="display:none"><a href="#" class="button big">Full Story</a></li>
</ul>
</article>
						</div>



                                            <div id="3d-flooring">
						<!-- Featured Post -->
							<article class="post featured">
								<header>
									<h1>3D Flooring</h1>

								</header>
								<a href="#" class="image main"><img src="images/gallery/showcase1.jpg?cache=7" alt="3d Flooring"/></a>
								<p>Have you ever imagined having a beach right in your leaving room? With the new technology of 3D floor designs, you can make it happen. You can bring sea waves, dolphins and corals, green lawns and flowers into your interior design that will transform your room into a place you dream of.

3D floor designs are the most innovative designs. In the base of these floors attractive 3D images that are covered with a liquid polymer material. Due to their low level of viscosity, floors create a smooth layer by themselves. That is why they are also called “self-levelling” polymer floors.
 </p>
                                                                <p>
They are not only a decorative element into modern interior design but also made of strong and ecologically safe materials. Polymer floors also have very high performances. Lifetime is dozens of years without changing its color. The environmental performance is conformed to all requirements.
A beautiful 3D image can be applied to children centers or any children’s rooms that should be clean and ecologically safe. Self-levelling floors do not have any seals where dirt and dust can be accumulated; they do not require big efforts while cleaning and are produced in accordance with sanitary norms. 3D floors are also practical and durable. They are able to withstand the weight of heavy furniture and a wide temperature range from -35C to +75C.
 </p>
                                                                <p>
It’s time to make your floor the central character of your interior design!</p>
                                                                <p>
Advantages:
 <br/>
<strong>Easy to clean:</strong> Polymeric coating is easily washable. No dirt or dust can be accumulated due to polyurethane coating stain-resistant.
 <br/>
 <strong>Hygienic:</strong> Due to polymeric coating stain-resistant, 3D flooring has fewer bacteria, fungi and other germs. Thus, favourable for families with small children.
  <br/>
  <strong>Anti-static:</strong> 3D flooring does not conduct electricity, therefore have excellent anti static characteristics.
  <br/>
  <strong>Heat Resistance:</strong> Any system of underfloor heating can be placed under 3D flooring.
  <br/>
  <strong>Monolithic:</strong> 3D flooring hasn't any joints or seams. </p>
                                                                <ul class="actions">
                                                                    <li style="display:none"><a href="#" class="button big">Full Story</a></li>
								</ul>
							</article>
                                            </div>
                                            <div id="3d-walls">
						<!-- Posts -->
                                                <article class="post featured">
									<header>
										<h1>3d Walls</h1>
									</header>
									<a href="#" class="image fit"><img src="images/gallery/0032.jpg" style="object-fit: cover" alt="3d Walls" height="409px" /></a>
									<p>True taster of comfort and beauty, stylish and fashionable, follow all the design innovations, because the house - this is the place where you want to come back to after a hard day, to relax and unwind. In our days so freshen the field of innovation interior is a decorative wall design - loading panels that help you get rid of a closed pressing sensation in the apartment due illusions "live" wall.
Most traditional materials for walls cannot compete with 3d walls that are able to create amazingly realistic figure and visual expand the space, filling it with unique color and mood.
Diversity of colors and patterns, a huge selection design options in establishing such original decorations in the interior as 3d wall, create spectacular "highlight", perfectly fit into the living room, bedroom, children's room, and bathroom, give a unique style in offices, restaurants, clubs and so on. A unique images, there is often a one-off, will be a way to impress your guests.
</p>
									<ul class="actions">
										<li style="display:none"><a href="#" class="button">Full Story</a></li>
									</ul>
								</article>
                                            </div>
                                            <div id="3d-ceiling">
								<article class="post featured">
                                                                    <header>
										<h1>3d Ceilling</h1>
									</header>
                                                                    <a href="#" class="image fit"><img src="images/gallery/showcase2.jpg" style="object-fit: cover" alt="3d Ceiling" height="409px" /></a>
									<p>3D Stretch ceiling is a special material with a smooth or embossed texture spanned by mounted on the perimeter of the room frame. The result is a perfectly smooth straight surface, which can be integrated point or any other fixtures.

                                                                            </p><p>The material for the manufacture of stretch ceiling is sturdy PVC film of various colors and textures, on which can be applied printing.

Enhanced recent specifications of 3D Ceilings made them very trendy and the most popular.

Appeared about 20 years ago, such ceilings quickly gained popularity in Europe thanks to its attractive appearance, durability and easy installation.

Fixed only 4 cm from the original ceiling, they do not reduce the height of the room and allow you to quickly and efficiently create a smooth, including multi-level surface.

</p><p>Quality 3D Ceilings can be used without restrictions in all areas:

   </p><p> - Offices, commercial and industrial halls;
</p><p>- In bedrooms, living rooms, bathrooms, hallways;
</p><p>- In swimming pools, sports complexes;
</p><p>- In hotels, restaurants, lobbies, conference rooms.
</p><p>At the same time there is always a possibility to choose ideal option. For smaller room’s relevant glossy surface for large rooms - matte and luxurious designs for bedrooms.

3D Ceilings visually expands the space, giving room majesty. Application of photo printing - a modern trend in the decoration of 3D Ceilings. This method of interior design allows for a truly unique design solutions in any room.

</p><p>Advantages of 3D Ceilings to other types of ceiling decoration:

 </p><p>- Longevity - a minimum warranty period - about 5 years, during which you can forget about cosmetic repairs;
 </p><p>- Humidity. 3D Ceilings are not afraid water leakage - even if the sheet is deformed under the weight of water, enough to unscrew the bulb, drain the water. The ceiling is dry and takes the old "commodity" form;
</p><p>- Easy installation that does not require global preparations, washing paint, alignment ceiling, "dirty" decorating, etc. Just an hour or two of work, the apartment will be a new, smooth and beautiful ceiling;
</p><p>- Versatility. A wide selection of colors and textures, allow such ceilings perfectly complement even the most extravagant interior;
</p><p>- Hygiene. 3D Stretch ceilings are made of antistatic material on which virtually no household dust settles. If necessary, the ceilings can be cleaned with a soft cloth using detergents. Given all the undeniable advantages, it is not surprising that the market for building materials, the production of 3D Ceilings with each year becomes more and more popular, and up to saturation of demand is still far away. Therefore, the production of 3D Ceilings - very promising and interesting idea for small and medium-sized businesses.</p>
									<ul class="actions">
										<li style="display:none"><a href="#" class="button">Full Story</a></li>
									</ul>
								</article>
                                            </div>

                                                <article class="post featured">
									<header>
                                                                            <h1 style="text-align: left">Properties</h1>
									</header>
									<a href="#" class="image fit"><img src="images/gallery/showcase3.jpg" alt="Properties" height="409px" /></a>
									<p>Basic properties of polymer flooring:
                                                                            </br>
1. Resistance to solar radiation (UV)
Our coatings has excellent resistance to solar radiation. Similar polymer on local market get to be yellow by the time.
</br></br>
2. Chemical resistance.
Epoxy floorings are non-absorbent easy to clean and demonstrate exceptional chemical resistance to: dilutions of organic and inorganic acids, solvents, alkalis, salts, petrochemical products, lubricants, aggressive cleaning agents, etc.
 </br></br>
            3. High mechanical strength.
Epoxy flooring systems are extremely resistant to mechanical wear, such as areas with increased traffic loadings (industrial production sites and storage facilities, parking sites, hotel lobbies, shopping malls, restaurants and bars, etc.)
They are characterized by:</br>
-       Increased resistance to abrasion, as to avoid dusting and wearing out.
</br>
-       Excellent compressive strength
</br>
-       High adhesion to the substrate, as to avoid delamination.
</br>
-       Major punctual hardness, as to avoid incising.

 </br></br>
4. Electrical conductivity
In areas there is an increasing demand to prevent the negative impact of the static electricity, such as computer rooms, printing houses, textile factories, hospitals, gas stations, power stations, etc. the instalment of conductive epoxy flooring systems is recommended.
 </br></br>
            5. Hygiene, easy-to-clean.
The epoxy flooring systems have been certified for their suitability for use in food process and food storage facilities, freezers, and hospitals, child cares etc., where the decision for a proper floor covering is determined by strict hygienic requirements. Furthermore, due to their smooth surface finish, they can be cleaned fast and easy.
 </br></br>
            6. Resistance to low and high temperatures.
Polymer floorings have been exposed to extreme weather conditions without abolishing their properties, if the temperature changes gradually. They are resistant to temperatures from -30°C to +100°C. Polymer flooring systems can be applied to both areas with low and high temperatures.   </p>
									<ul class="actions">
										<li style="display:none"><a href="#" class="button">Full Story</a></li>
									</ul>
                                                                </article>
																																<div id="gallery">
																																	<header>
																																	<h1>Gallery</h1>
																																	<p>Some pictures to inspire you ...</p>
																																	</header>

																																	<section class="posts">

																																<!-- Posts -->
																																			<?php
																																			if (!empty($pageData['gallery_image_urls'])) {
																																				foreach($pageData['gallery_image_urls'] as $imgurl) {
																																					echo "<article><img src='$imgurl' width='400px' height='300px'/></article>\n";
																																				}
																																			}
																																			?>
																														</section>
																															</div>

						<!-- Footer -->
							<footer>
								<div class="pagination" style="display:none">
									<!--<a href="#" class="previous">Prev</a>-->
									<a href="#" class="page active">1</a>
									<a href="#" class="page">2</a>
									<a href="#" class="page">3</a>
									<span class="extra">&hellip;</span>
									<a href="#" class="page">8</a>
									<a href="#" class="page">9</a>
									<a href="#" class="page">10</a>
									<a href="#" class="next">Next</a>
								</div>
							</footer>

					</div>

				<!-- Footer -->
                                <div id="contact-us">


					<footer id="footer">
						<section>
                                                    <header>
										<h1>Contact Us</h1>
									</header>
							<form method="post" action="/" name="contact">
								<div class="field">
									<label for="name">Name</label>
									<input type="text" name="name" id="name" />
								</div>
								<div class="field">
									<label for="email">Email</label>
									<input type="text" name="email" id="email" />
								</div>
								<div class="field">
									<label for="message">Message</label>
									<textarea name="message" id="message" rows="3"></textarea>
								</div>
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</form>
						</section>
						<section class="split contact">
							<section class="alt">
								<h3>Address</h3>
								<p>Montreal, Quebec<br />
								</p>
							</section>
							<section>
								<h3>Phone</h3>
								<p>(514) 969-1440/p>
							</section>
							<section>
								<h3>Email</h3>
								<p>stepon3d@gmail.com</p>
							</section>
							<section>
								<h3>Social</h3>
								<ul class="icons alt">
									<!-- <li><a href="#" class="icon alt fa-twitter"><span class="label">Twitter</span></a></li> -->
									<li><a href="https://www.facebook.com/3dflooringmontreal/" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
									<!-- <li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li> -->
									<!-- <li><a href="#" class="icon alt fa-github"><span class="label">GitHub</span></a></li> -->
								</ul>
							</section>
						</section>

					</footer></div>

				<!-- Copyright -->
					<div id="copyright">
						<ul><li>&copy; 3D World INC. 2017 | No Animals were harmed in the making of this site. | HTML5 UP</li></ul>
					</div>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
